# build vue
FROM node:20-alpine as build-stage

RUN apk update && apk upgrade

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# nginx
FROM nginx:stable-alpine

RUN apk update && apk upgrade

COPY --from=build-stage /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

# Ekspos port 80 untuk HTTP
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]